/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.iesjandula.pokemon_game;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import es.iesjandula.pokemon_game.models.Pokemon;
import es.iesjandula.pokemon_game.utils.PokemonException;
import lombok.Data;

/**
 *
 * @author David Martinez Flores
 */
@Data
public class PlayerOneSelection extends javax.swing.JFrame implements Serializable
{
	/** Attribute logger */
	private static final Logger logger = LogManager.getLogger();

	/** Attribute playerOneName */
	private String playerOneName;

	/** Attribute mainTheme */
	private Clip mainTheme;

	/** Attribute temporalListModel */
	private DefaultListModel<Pokemon> temporalListModel = new DefaultListModel<>();

	/** Attribute listModel */
	private DefaultListModel<Pokemon> listModel = new DefaultListModel<>();

	/** Attribute listModel2 */
	private DefaultListModel<Pokemon> listModel2 = new DefaultListModel<>();

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel SpriteSelectedPlayerOne;
	private javax.swing.ButtonGroup buttonGroupPlayerOneSprite;
	private javax.swing.JButton jButtonRandom;
	private javax.swing.JButton jButtonRemove;
	private javax.swing.JButton jButtonRemoveAll;
	private javax.swing.JButton jButtonResetFilter;
	private javax.swing.JButton jButtonSelect;
	private javax.swing.JButton jButtonSelectionComplete;
	private javax.swing.JLabel jLabelAttack;
	private javax.swing.JLabel jLabelBackground;
	private javax.swing.JLabel jLabelChoseYourPokemon;
	private javax.swing.JLabel jLabelDeffense;
	private javax.swing.JLabel jLabelFilter;
	private javax.swing.JLabel jLabelHelath;
	private javax.swing.JLabel jLabelPlayerName;
	private javax.swing.JLabel jLabelPlayerOneName;
	private javax.swing.JLabel jLabelSpAttack;
	private javax.swing.JLabel jLabelSpDefense;
	private javax.swing.JLabel jLabelSpeed;
	private javax.swing.JList<Pokemon> jListAllPokes;
	private javax.swing.JList<Pokemon> jListSelectedPokes;
	private javax.swing.JMenu jMenu;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItemLoad;
	private javax.swing.JRadioButton jRadioButtonBlue;
	private javax.swing.JRadioButton jRadioButtonFemaleRanger;
	private javax.swing.JRadioButton jRadioButtonNormalFemale;
	private javax.swing.JRadioButton jRadioButtonRanger;
	private javax.swing.JRadioButton jRadioButtonRed;
	private javax.swing.JScrollPane jScrollPane;
	private javax.swing.JScrollPane jScrollPaneTwo;
	private javax.swing.JTextField jTextFieldFilter;
	private javax.swing.JTextField jTextFieldPlayerName;
	// End of variables declaration//GEN-END:variables

	/**
	 * Creates new form MainJFrmae
	 *
	 * @param clip
	 */
	public PlayerOneSelection(Clip clip)
	{
		// ---THE ORDER ITS IMPORTANT---
		this.initComponents();
		this.setTitle("Player One Selection");
		this.setIconImage(Toolkit.getDefaultToolkit().getImage("./images/pokeball.png"));

		this.jLabelBackground.setIcon(new ImageIcon("./images/selectionBack2.jpg"));
		this.SpriteSelectedPlayerOne.setIcon(new ImageIcon("./images/red.png"));
		this.playerOneName = "Player One";
		this.jLabelPlayerName.setText(this.playerOneName);
		this.listModel.addAll(this.loadAllPokemons());
		this.jListAllPokes.setModel(this.listModel);
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.mainTheme = clip;
		this.jumpPokemonAnimationThread();
	}

	/**
	 * Method loadAllPokemons Load the pokemons from Application
	 *
	 * @return List<Pokemon>
	 */
	private List<Pokemon> loadAllPokemons()
	{
		Application application = new Application();

		return application.getPokemonList();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		this.buttonGroupPlayerOneSprite = new javax.swing.ButtonGroup();
		this.jScrollPane = new javax.swing.JScrollPane();
		this.jListAllPokes = new javax.swing.JList<>();
		this.jButtonSelect = new javax.swing.JButton();
		this.jScrollPaneTwo = new javax.swing.JScrollPane();
		this.jListSelectedPokes = new javax.swing.JList<>();
		this.jLabelChoseYourPokemon = new javax.swing.JLabel();
		this.jButtonRemove = new javax.swing.JButton();
		this.jButtonRemoveAll = new javax.swing.JButton();
		this.jLabelHelath = new javax.swing.JLabel();
		this.jLabelAttack = new javax.swing.JLabel();
		this.jLabelDeffense = new javax.swing.JLabel();
		this.jLabelSpAttack = new javax.swing.JLabel();
		this.jLabelSpDefense = new javax.swing.JLabel();
		this.jLabelSpeed = new javax.swing.JLabel();
		this.jButtonSelectionComplete = new javax.swing.JButton();
		this.jTextFieldFilter = new javax.swing.JTextField();
		this.jLabelFilter = new javax.swing.JLabel();
		this.jButtonResetFilter = new javax.swing.JButton();
		this.jTextFieldPlayerName = new javax.swing.JTextField();
		this.jLabelPlayerOneName = new javax.swing.JLabel();
		this.jLabelPlayerName = new javax.swing.JLabel();
		this.jRadioButtonRed = new javax.swing.JRadioButton();
		this.jRadioButtonBlue = new javax.swing.JRadioButton();
		this.SpriteSelectedPlayerOne = new javax.swing.JLabel();
		this.jRadioButtonRanger = new javax.swing.JRadioButton();
		this.jRadioButtonFemaleRanger = new javax.swing.JRadioButton();
		this.jRadioButtonNormalFemale = new javax.swing.JRadioButton();
		this.jButtonRandom = new javax.swing.JButton();
		this.jLabelBackground = new javax.swing.JLabel();
		this.jMenuBar1 = new javax.swing.JMenuBar();
		this.jMenu = new javax.swing.JMenu();
		this.jMenuItemLoad = new javax.swing.JMenuItem();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		this.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
		this.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		this.jListAllPokes.setBackground(new java.awt.Color(200, 252, 255));
		this.jListAllPokes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		this.jListAllPokes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jListAllPokes.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerOneSelection.this.jListAllPokesMouseClicked(evt);
			}
		});
		this.jScrollPane.setViewportView(this.jListAllPokes);

		this.getContentPane().add(this.jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 421, 273));

		this.jButtonSelect.setBackground(new java.awt.Color(51, 153, 0));
		this.jButtonSelect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jButtonSelect.setForeground(new java.awt.Color(255, 255, 255));
		this.jButtonSelect.setText("SELECT");
		this.jButtonSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonSelect.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerOneSelection.this.jButtonSelectMouseClicked(evt);
			}
		});
		this.getContentPane().add(this.jButtonSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 326, -1, -1));

		this.jListSelectedPokes.setBackground(new java.awt.Color(227, 227, 227));
		this.jListSelectedPokes.setForeground(new java.awt.Color(0, 102, 0));
		this.jListSelectedPokes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jListSelectedPokes.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerOneSelection.this.jListSelectedPokesMouseClicked(evt);
			}
		});
		this.jScrollPaneTwo.setViewportView(this.jListSelectedPokes);

		this.getContentPane().add(this.jScrollPaneTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 41, 419, 273));

		this.jLabelChoseYourPokemon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		this.jLabelChoseYourPokemon.setText("         CHOOSE YOUR POKEMON!");
		this.jLabelChoseYourPokemon
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		this.jLabelChoseYourPokemon.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
		this.getContentPane().add(this.jLabelChoseYourPokemon,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 355, 363, 165));

		this.jButtonRemove.setBackground(new java.awt.Color(255, 153, 102));
		this.jButtonRemove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jButtonRemove.setForeground(new java.awt.Color(255, 255, 255));
		this.jButtonRemove.setText("REMOVE");
		this.jButtonRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonRemove.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerOneSelection.this.jButtonRemoveMouseClicked(evt);
			}
		});
		this.getContentPane().add(this.jButtonRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 326, -1, -1));

		this.jButtonRemoveAll.setBackground(new java.awt.Color(255, 0, 51));
		this.jButtonRemoveAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jButtonRemoveAll.setForeground(new java.awt.Color(255, 255, 255));
		this.jButtonRemoveAll.setText("REMOVE ALL");
		this.jButtonRemoveAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonRemoveAll.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerOneSelection.this.jButtonRemoveAllMouseClicked(evt);
			}
		});
		this.getContentPane().add(this.jButtonRemoveAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 326, -1, -1));

		this.jLabelHelath.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelHelath.setForeground(new java.awt.Color(0, 117, 0));
		this.jLabelHelath.setText("HEALTH");
		this.jLabelHelath.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelHelath.setOpaque(true);
		this.getContentPane().add(this.jLabelHelath, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 355, 111, -1));

		this.jLabelAttack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelAttack.setForeground(new java.awt.Color(255, 0, 0));
		this.jLabelAttack.setText("ATTACK");
		this.jLabelAttack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelAttack.setOpaque(true);
		this.getContentPane().add(this.jLabelAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 381, 94, -1));

		this.jLabelDeffense.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelDeffense.setForeground(new java.awt.Color(51, 51, 255));
		this.jLabelDeffense.setText("DEFENSE");
		this.jLabelDeffense.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelDeffense.setOpaque(true);
		this.getContentPane().add(this.jLabelDeffense, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 433, 111, -1));

		this.jLabelSpAttack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelSpAttack.setForeground(new java.awt.Color(255, 102, 0));
		this.jLabelSpAttack.setText("SP-ATTACK");
		this.jLabelSpAttack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelSpAttack.setOpaque(true);
		this.getContentPane().add(this.jLabelSpAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 407, 111, -1));

		this.jLabelSpDefense.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelSpDefense.setForeground(new java.awt.Color(0, 204, 204));
		this.jLabelSpDefense.setText("SP-DEFENSE");
		this.jLabelSpDefense.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelSpDefense.setOpaque(true);
		this.getContentPane().add(this.jLabelSpDefense, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 459, 140, -1));

		this.jLabelSpeed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelSpeed.setForeground(new java.awt.Color(248, 0, 243));
		this.jLabelSpeed.setText("SPEED");
		this.jLabelSpeed.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelSpeed.setOpaque(true);
		this.getContentPane().add(this.jLabelSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 485, 111, -1));

		this.jButtonSelectionComplete.setBackground(new java.awt.Color(51, 204, 0));
		this.jButtonSelectionComplete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jButtonSelectionComplete.setForeground(new java.awt.Color(255, 255, 255));
		this.jButtonSelectionComplete.setText("SELECTION COMPLETE");
		this.jButtonSelectionComplete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonSelectionComplete.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerOneSelection.this.jButtonSelectionCompleteMouseClicked(evt);
			}
		});
		this.getContentPane().add(this.jButtonSelectionComplete,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 526, -1, 46));

		this.jTextFieldFilter.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerOneSelection.this.jTextFieldFilterActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jTextFieldFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 6, 136, -1));

		this.jLabelFilter.setBackground(new java.awt.Color(255, 204, 102));
		this.jLabelFilter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jLabelFilter.setText("FILTER:");
		this.jLabelFilter.setOpaque(true);
		this.getContentPane().add(this.jLabelFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 9, -1, -1));

		this.jButtonResetFilter.setText("RESET FILTER");
		this.jButtonResetFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonResetFilter.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerOneSelection.this.jButtonResetFilterActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jButtonResetFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 6, -1, -1));

		this.jTextFieldPlayerName.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerOneSelection.this.jTextFieldPlayerNameActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jTextFieldPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 6, 116, -1));

		this.jLabelPlayerOneName.setBackground(new java.awt.Color(255, 204, 102));
		this.jLabelPlayerOneName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jLabelPlayerOneName.setText("Player One Name:");
		this.jLabelPlayerOneName.setOpaque(true);
		this.getContentPane().add(this.jLabelPlayerOneName, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 9, -1, -1));

		this.jLabelPlayerName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		this.jLabelPlayerName.setText("       ");
		this.getContentPane().add(this.jLabelPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 9, 207, 20));

		this.buttonGroupPlayerOneSprite.add(this.jRadioButtonRed);
		this.jRadioButtonRed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jRadioButtonRed.setSelected(true);
		this.jRadioButtonRed.setText("Red");
		this.jRadioButtonRed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jRadioButtonRed.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerOneSelection.this.jRadioButtonRedActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jRadioButtonRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 381, -1, -1));

		this.buttonGroupPlayerOneSprite.add(this.jRadioButtonBlue);
		this.jRadioButtonBlue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jRadioButtonBlue.setText("Blue");
		this.jRadioButtonBlue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jRadioButtonBlue.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerOneSelection.this.jRadioButtonBlueActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jRadioButtonBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 414, -1, -1));

		this.SpriteSelectedPlayerOne.setText(" ");
		this.getContentPane().add(this.SpriteSelectedPlayerOne,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 355, 136, 196));

		this.buttonGroupPlayerOneSprite.add(this.jRadioButtonRanger);
		this.jRadioButtonRanger.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jRadioButtonRanger.setText("Ranger");
		this.jRadioButtonRanger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jRadioButtonRanger.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerOneSelection.this.jRadioButtonRangerActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jRadioButtonRanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 443, -1, -1));

		this.buttonGroupPlayerOneSprite.add(this.jRadioButtonFemaleRanger);
		this.jRadioButtonFemaleRanger.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jRadioButtonFemaleRanger.setText("Female Ranger");
		this.jRadioButtonFemaleRanger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jRadioButtonFemaleRanger.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerOneSelection.this.jRadioButtonFemaleRangerActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jRadioButtonFemaleRanger,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 472, -1, -1));

		this.buttonGroupPlayerOneSprite.add(this.jRadioButtonNormalFemale);
		this.jRadioButtonNormalFemale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jRadioButtonNormalFemale.setText("Normal Female");
		this.jRadioButtonNormalFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jRadioButtonNormalFemale.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerOneSelection.this.jRadioButtonNormalFemaleActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jRadioButtonNormalFemale,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 499, -1, -1));

		this.jButtonRandom.setBackground(new java.awt.Color(255, 0, 255));
		this.jButtonRandom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jButtonRandom.setForeground(new java.awt.Color(255, 255, 255));
		this.jButtonRandom.setText("RANDOM");
		this.jButtonRandom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonRandom.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerOneSelection.this.jButtonRandomActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jButtonRandom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 30));
		this.getContentPane().add(this.jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 610));

		this.jMenu.setText("File");

		this.jMenuItemLoad.setText("Load State");
		this.jMenuItemLoad.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerOneSelection.this.jMenuItemLoadActionPerformed(evt);
			}
		});
		this.jMenu.add(this.jMenuItemLoad);

		this.jMenuBar1.add(this.jMenu);

		this.setJMenuBar(this.jMenuBar1);

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Method jButtonRandomActionPerformed Generate five random pokemons to the
	 * player selection pokemons
	 *
	 * @param evt
	 */
	private void jButtonRandomActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton6ActionPerformed
		int random = (int) ((Math.random() * 721) + 1);
		PlayerOneSelection.logger.info(random);
		List<Pokemon> randomList = new ArrayList<>();

		for (int i = 0; i < 5; i++)
		{
			random = (int) ((Math.random() * 721) + 1);
			randomList.add(this.listModel.get(random));
		}
		this.listModel2 = new DefaultListModel<>();
		this.listModel2.addAll(randomList);
		this.jListSelectedPokes.setModel(this.listModel2);
	}// GEN-LAST:event_jButton6ActionPerformed

	/**
	 * Method jTextFieldFilterActionPerformed That is used for filter the principal
	 * pokemon list
	 *
	 * @param evt
	 */
	private void jTextFieldFilterActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jTextField1ActionPerformed
		PlayerOneSelection.logger.info("Presiono Enter");
		this.temporalListModel = new DefaultListModel<>();

		for (int i = 0; i < this.listModel.size(); i++)
		{
			if (this.listModel.get(i).getName().toLowerCase().contains(this.jTextFieldFilter.getText().toLowerCase()))
			{
				this.temporalListModel.add(0, this.listModel.get(i));
			}
		}

		this.jListAllPokes.setModel(this.temporalListModel);
	}// GEN-LAST:event_jTextField1ActionPerformed

	/**
	 * Method jButtonResetFilterActionPerformed Used for reset the filters
	 *
	 * @param evt
	 */
	private void jButtonResetFilterActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton5ActionPerformed
		this.jListAllPokes.setModel(this.listModel);
		this.jTextFieldFilter.setText("");
	}// GEN-LAST:event_jButton5ActionPerformed

	/**
	 * Method jTextFieldPlayerNameActionPerformed Used for set the player name but
	 * with specific settings
	 *
	 * @param evt
	 */
	private void jTextFieldPlayerNameActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jTextField2ActionPerformed

		// --TRIM FOR DELETE EMPTY NAMES AND SPACES---
		this.playerOneName = this.jTextFieldPlayerName.getText().trim();

		//
		if ((this.playerOneName.length() <= 16) && !this.playerOneName.isEmpty())
		{
			this.jLabelPlayerName.setText(this.playerOneName);
		}
		else
		{
			JOptionPane.showMessageDialog(null, "The selected name is too big or empty (16 chars max)");
		}
	}// GEN-LAST:event_jTextField2ActionPerformed

	/**
	 * Method jRadioButtonRedActionPerformed Change the sprite
	 *
	 * @param evt
	 */
	private void jRadioButtonRedActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jRadioButton1ActionPerformed
		this.SpriteSelectedPlayerOne.setIcon(new ImageIcon("./images/red.png"));
	}// GEN-LAST:event_jRadioButton1ActionPerformed

	/**
	 * Method jRadioButtonBlueActionPerformed Change the sprite
	 *
	 * @param evt
	 */
	private void jRadioButtonBlueActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jRadioButton2ActionPerformed
		this.SpriteSelectedPlayerOne.setIcon(new ImageIcon("./images/blue.png"));
	}// GEN-LAST:event_jRadioButton2ActionPerformed

	/**
	 * Method jRadioButtonRangerActionPerformed Change the sprite
	 *
	 * @param evt
	 */
	private void jRadioButtonRangerActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jRadioButton3ActionPerformed
		this.SpriteSelectedPlayerOne.setIcon(new ImageIcon("./images/ranger.png"));
	}// GEN-LAST:event_jRadioButton3ActionPerformed

	/**
	 * Method jRadioButtonFemaleRangerActionPerformed Change the sprite
	 *
	 * @param evt
	 */
	private void jRadioButtonFemaleRangerActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jRadioButton4ActionPerformed
		this.SpriteSelectedPlayerOne.setIcon(new ImageIcon("./images/femaleRanger.png"));
	}// GEN-LAST:event_jRadioButton4ActionPerformed

	/**
	 * Method jRadioButtonNormalFemaleActionPerformed Change the sprite
	 *
	 * @param evt
	 */
	private void jRadioButtonNormalFemaleActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jRadioButton5ActionPerformed
		this.SpriteSelectedPlayerOne.setIcon(new ImageIcon("./images/normalFemale.png"));
	}// GEN-LAST:event_jRadioButton5ActionPerformed

	/**
	 * Method jMenuItemLoadActionPerformed Used for load the saved state
	 *
	 * @param evt
	 */
	private void jMenuItemLoadActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jMenuItem1ActionPerformed
		PlayerOneSelection.logger.info("CARGAR ESTADO");
		Application application = new Application();

		// ---USE A LIST OF OBJECTS TO LOAD ALL----
		List<Object> partyList = null;
		try
		{
			partyList = application.loadState();
		}
		catch (PokemonException exception)
		{
			String error = "An Error Ocurred on the application loading State";
			PlayerOneSelection.logger.error(error, exception);
		}

		if (partyList != null)
		{
			// ---IF THE LOAD ITS COMPLETED , LAUNCH PLAYER VERSUS PLAYER WINDOW WITH THE
			// PARTY LIST---
			this.mainTheme.stop();
			PlayerVersusPlayer loadedPlayerVersusPlayer = new PlayerVersusPlayer(partyList);
			loadedPlayerVersusPlayer.setVisible(true);
			PlayerOneSelection.logger.info(partyList);
			this.dispose();
			JOptionPane.showMessageDialog(null, "STATE DATA LOADED!");

		}
		else
		{
			JOptionPane.showMessageDialog(null, "THE STATE IS CORRUPTED OR DONT EXISTS ANY STATE!");
		}
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	/**
	 * Method jButtonRemoveMouseClicked Remove selected pokemon
	 *
	 * @param evt
	 */
	private void jButtonRemoveMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jButton2MouseClicked
		this.selectButtonSound();
		Pokemon selectedPokemon = this.jListSelectedPokes.getSelectedValue();

		if (this.listModel2.contains(selectedPokemon))
		{
			for (int i = 0; i < this.listModel2.size(); i++)
			{
				Pokemon temporalPokemon = this.listModel2.get(i);
				if (temporalPokemon.equals(selectedPokemon))
				{
					this.listModel2.remove(i);
				}
			}
		}
	}// GEN-LAST:event_jButton2MouseClicked

	/**
	 * Method jButtonRemoveAllMouseClicked Remove all selected pokemons
	 *
	 * @param evt
	 */
	private void jButtonRemoveAllMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jButton3MouseClicked
		this.selectButtonSound();
		this.listModel2.removeAllElements();
	}// GEN-LAST:event_jButton3MouseClicked

	/**
	 * Method jListAllPokesMouseClicked Getting the pokemon selected on all pokemon
	 * list to show the data on the labels
	 *
	 * @param evt
	 */
	private void jListAllPokesMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jList1MouseClicked
		this.selectButtonSound();
		Pokemon selectedPokemon = this.jListAllPokes.getSelectedValue();
		ImageIcon icon = new ImageIcon(selectedPokemon.getPokeImage());
		this.jLabelChoseYourPokemon.setIcon(icon);
		this.jLabelChoseYourPokemon.setText(selectedPokemon.getName());

		this.jLabelHelath.setText("Health: " + selectedPokemon.getHealth());
		this.jLabelAttack.setText("Attack: " + selectedPokemon.getAttack());
		this.jLabelDeffense.setText("SP-Attack: " + selectedPokemon.getSpAttack());
		this.jLabelSpAttack.setText("Defense: " + selectedPokemon.getDefense());
		this.jLabelSpDefense.setText("SP-Defense: " + selectedPokemon.getSpDefense());
		this.jLabelSpeed.setText("Speed: " + selectedPokemon.getSpeed());
		this.repaint();

	}// GEN-LAST:event_jList1MouseClicked

	/**
	 * Method jListSelectedPokesMouseClicked Getting the pokemon selected on
	 * selected pokemon list to show the data on the labels
	 *
	 * @param evt
	 */
	private void jListSelectedPokesMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jList2MouseClicked
		Pokemon selectedPokemon = this.jListSelectedPokes.getSelectedValue();
		this.selectButtonSound();
		if (selectedPokemon != null)
		{
			ImageIcon icon = new ImageIcon(selectedPokemon.getPokeImage());
			this.jLabelChoseYourPokemon.setIcon(icon);
			this.jLabelChoseYourPokemon.setText(selectedPokemon.getName());

			this.jLabelHelath.setText("Health: " + selectedPokemon.getHealth());
			this.jLabelAttack.setText("Attack: " + selectedPokemon.getAttack());
			this.jLabelDeffense.setText("SP-Attack: " + selectedPokemon.getSpAttack());
			this.jLabelSpAttack.setText("Defense: " + selectedPokemon.getDefense());
			this.jLabelSpDefense.setText("SP-Defense: " + selectedPokemon.getSpDefense());
			this.jLabelSpeed.setText("Speed: " + selectedPokemon.getSpeed());
			this.repaint();
		}
	}// GEN-LAST:event_jList2MouseClicked

	/**
	 * Method jButtonSelectionCompleteMouseClicked Used for end the player one
	 * selection
	 *
	 * @param evt
	 */
	private void jButtonSelectionCompleteMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jButton4MouseClicked
		this.selectButtonSound();
		// --ONLY PASS IF THE POKEMONS ARE MORE THAN 0---
		if (this.listModel2.size() > 0)
		{
			PlayerTwoSelection playerTwoSelection = new PlayerTwoSelection(this);
			playerTwoSelection.setVisible(true);
			this.dispose();
		}
		else
		{
			// ---SHOW POP UP WARNING---
			JOptionPane.showMessageDialog(this, "!OH , YOU NEED CHOOSE MINIMUM 1 POKEMON!");
			this.jLabelPlayerName.setText("Player One");
		}
	}// GEN-LAST:event_jButton4MouseClicked

	/**
	 * Method jButtonSelectMouseClicked Get the selected pokemon
	 *
	 * @param evt
	 */
	private void jButtonSelectMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jButton1MouseClicked
		this.selectButtonSound();
		Pokemon selectedPokemon = this.jListAllPokes.getSelectedValue();

		// --IF THE SELECTED POKEMON ARREADY EXIST ON SELECTED POKEMONS , SHOW POP UP
		// WARNING
		if (this.listModel2.contains(selectedPokemon))
		{
			JOptionPane.showMessageDialog(this, "You alrready select " + selectedPokemon.getName());
		}
		else if (this.listModel2.size() < 5)
		{
			this.listModel2.add(0, selectedPokemon);
			this.jListSelectedPokes.setModel(this.listModel2);
			PlayerOneSelection.logger.info(this.listModel2);
		}
		else
		{
			JOptionPane.showMessageDialog(this, "You have 5 Pokemons selected!");
		}

	}// GEN-LAST:event_jButton1MouseClicked

	/**
	 * Method selectButtonSound The button sounds
	 */
	private void selectButtonSound()
	{

		AudioInputStream audioInputStream = null;
		try
		{
			audioInputStream = AudioSystem.getAudioInputStream(new File("./audio/butonSelect.wav"));
			Clip clip = AudioSystem.getClip();
			clip.open(audioInputStream);
			clip.start();

		}
		catch (UnsupportedAudioFileException exception)
		{
			String error = "UnsupportedAudioFileException";
			PlayerOneSelection.logger.error(error, exception);
		}
		catch (IOException exception)
		{
			String error = "IOException";
			PlayerOneSelection.logger.error(error, exception);
		}
		catch (LineUnavailableException exception)
		{
			String error = "LineUnavailableException";
			PlayerOneSelection.logger.error(error, exception);
		}
		finally
		{
			try
			{
				audioInputStream.close();
			}
			catch (IOException exception)
			{
				String error = "IOException";
				PlayerOneSelection.logger.error(error, exception);
			}
		}
	}

	/**
	 * Method jumpPokemonAnimationThread Jump pokemon animation
	 */
	private void jumpPokemonAnimationThread()
	{
		Thread jumpThread = new Thread(new Runnable()
		{
			@Override
			public void run()
			{
				int speed = 1;
				// ---INFINITE LOOP FOR INFINITE ANIMATION---
				while (true)
				{
					for (int i = 0; i < 10; i++)
					{

						PlayerOneSelection.this.jLabelChoseYourPokemon.setLocation(
								PlayerOneSelection.this.jLabelChoseYourPokemon.getX(),
								PlayerOneSelection.this.jLabelChoseYourPokemon.getY() + speed);
						try
						{
							Thread.sleep(100);
						}
						catch (InterruptedException exception)
						{
							String error = "InterruptedException";
							PlayerOneSelection.logger.error(error, exception);
						}
					}
					for (int i = 0; i < 10; i++)
					{

						PlayerOneSelection.this.jLabelChoseYourPokemon.setLocation(
								PlayerOneSelection.this.jLabelChoseYourPokemon.getX(),
								PlayerOneSelection.this.jLabelChoseYourPokemon.getY() + (speed * -1));
						try
						{
							Thread.sleep(100);
						}
						catch (InterruptedException exception)
						{
							String error = "InterruptedException";
							PlayerOneSelection.logger.error(error, exception);
						}
					}
				}
			}
		});
		jumpThread.start();
	}
}