/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.iesjandula.pokemon_game;

import es.iesjandula.pokemon_game.models.Pokemon;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author David Martinez Flores
 */
public class PlayerVersusPlayer extends javax.swing.JFrame {
        private PlayerOneSelection playerOneSelection;
        private PlayerTwoSelection playerTwoSelection;
        
    	private DefaultListModel<Pokemon> listPlayerOne = new DefaultListModel<>();
	private DefaultListModel<Pokemon> listPlayerTwo = new DefaultListModel<>();
        
        private ImageIcon iconPlayer1;
        private ImageIcon iconPlayer2;
        
        private Pokemon currentPlayerOnePokemon;
        private Pokemon currentPlayerTwoPokemon;

    /**
     * Creates new form PlayerVersusPlayer
     */
    public PlayerVersusPlayer(PlayerTwoSelection playerTwoSelection) {
        playerTwoSelection.dispose();
        initComponents();
        this.jLabel3.setIcon(new ImageIcon("./images/versus.png"));
        
        this.playerOneSelection=playerTwoSelection.getPlayerOneSelection();
        this.playerTwoSelection=playerTwoSelection;
        
        this.listPlayerOne=this.playerOneSelection.getListModel2();
        this.listPlayerTwo=this.playerTwoSelection.getListModel2();
        
        this.jList1.setModel(listPlayerOne);
        this.jList2.setModel(listPlayerTwo);
        
        this.iconPlayer1= new ImageIcon(this.listPlayerOne.get(0).getPokeImage());
        this.iconPlayer2= new ImageIcon(this.listPlayerTwo.get(0).getPokeImage());
        
        
        this.jLabel1.setText(this.listPlayerOne.get(0).getName());
        this.jLabel2.setText(this.listPlayerTwo.get(0).getName());
        
        this.jLabel1.setIcon(this.iconPlayer1);
        this.jLabel2.setIcon(this.iconPlayer2);

        this.currentPlayerOnePokemon=this.listPlayerOne.get(0);
        this.currentPlayerTwoPokemon=this.listPlayerTwo.get(0);
        
        this.jLabel4Player1Health.setText(currentPlayerOnePokemon.getHealth()+"");
        this.jLabel5Player2Health.setText(currentPlayerTwoPokemon.getHealth()+"");
        
        
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1Attack = new javax.swing.JButton();
        jButton2SpAttack = new javax.swing.JButton();
        jButton3Attack = new javax.swing.JButton();
        jButton4SpAttack = new javax.swing.JButton();
        jLabel4Player1Health = new javax.swing.JLabel();
        jLabel5Player2Health = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("                ");

        jButton1Attack.setText(" PHYSICAL ATTACK");
        jButton1Attack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1AttackMouseClicked(evt);
            }
        });
        jButton1Attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AttackActionPerformed(evt);
            }
        });

        jButton2SpAttack.setText(" SPECIAL ATTACK");
        jButton2SpAttack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2SpAttackMouseClicked(evt);
            }
        });
        jButton2SpAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2SpAttackActionPerformed(evt);
            }
        });

        jButton3Attack.setText(" PHYSICAL ATTACK");
        jButton3Attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3AttackActionPerformed(evt);
            }
        });

        jButton4SpAttack.setText(" SPECIAL ATTACK");
        jButton4SpAttack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4SpAttackMouseClicked(evt);
            }
        });
        jButton4SpAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4SpAttackActionPerformed(evt);
            }
        });

        jLabel4Player1Health.setText("jLabel4");

        jLabel5Player2Health.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1Attack)
                                    .addComponent(jButton2SpAttack))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3Attack, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4SpAttack, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel4Player1Health)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5Player2Health)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4Player1Health)
                    .addComponent(jLabel5Player2Health))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1Attack)
                    .addComponent(jButton3Attack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2SpAttack)
                    .addComponent(jButton4SpAttack))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2SpAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SpAttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2SpAttackActionPerformed

    private void jButton4SpAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4SpAttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4SpAttackActionPerformed

    private void jButton1AttackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1AttackMouseClicked
        //Getting the current poke position
        int position=0;
        for(int i =0;i<this.listPlayerTwo.size();i++)
        {
            if(this.currentPlayerTwoPokemon.equals(this.listPlayerTwo.get(i)))
            {
                position=i;
                break;
            }
        }
        
        //Caculate the health
        this.currentPlayerTwoPokemon.setHealth(this.currentPlayerTwoPokemon.getHealth()+((this.currentPlayerOnePokemon.getAttack()*-0.4)+this.currentPlayerTwoPokemon.getDefense()*0.1));
        //Setting the current poke with new values
        this.listPlayerTwo.set(position, this.currentPlayerTwoPokemon);
        
        //If the poke die, get automaticaly the last poke
        if(this.currentPlayerTwoPokemon.getHealth()<=0 && (this.listPlayerTwo.size()>0 && this.listPlayerOne.size()>0))
        {
            this.listPlayerTwo.remove(position);
            this.currentPlayerTwoPokemon=this.listPlayerTwo.get(this.listPlayerTwo.size()-1);
            this.jLabel2.setIcon(new ImageIcon(this.currentPlayerTwoPokemon.getPokeImage()));
        }
        //Update the health text and repaint the PlayerVersusPlayer
        this.jLabel2.setText(this.currentPlayerTwoPokemon.getName());
        this.jLabel5Player2Health.setText(currentPlayerTwoPokemon.getHealth()+"");
        this.repaint();
    }//GEN-LAST:event_jButton1AttackMouseClicked

    private void jButton1AttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AttackActionPerformed

    private void jButton3AttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3AttackActionPerformed
        int position=0;
        for(int i =0;i<this.listPlayerOne.size();i++)
        {
            if(this.currentPlayerOnePokemon.equals(this.listPlayerOne.get(i)))
            {
                position=i;
                break;
            }
        }
        
        this.currentPlayerOnePokemon.setHealth(this.currentPlayerOnePokemon.getHealth()+((this.currentPlayerTwoPokemon.getAttack()*-0.4)+this.currentPlayerOnePokemon.getDefense()*0.1));
        this.listPlayerOne.set(position, this.currentPlayerOnePokemon);
        if(this.currentPlayerOnePokemon.getHealth()<=0 && (this.listPlayerTwo.size()>0 && this.listPlayerOne.size()>0))
        {
            this.listPlayerOne.remove(position);
            this.currentPlayerOnePokemon=this.listPlayerOne.get(this.listPlayerOne.size()-1);
            this.jLabel1.setIcon(new ImageIcon(this.currentPlayerOnePokemon.getPokeImage()));
        }
        this.jLabel1.setText(this.currentPlayerOnePokemon.getName());
        this.jLabel4Player1Health.setText(this.currentPlayerOnePokemon.getHealth()+"");
        this.repaint();
    }//GEN-LAST:event_jButton3AttackActionPerformed

    private void jButton2SpAttackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2SpAttackMouseClicked
      int position=0;
        for(int i =0;i<this.listPlayerTwo.size();i++)
        {
            if(this.currentPlayerTwoPokemon.equals(this.listPlayerTwo.get(i)))
            {
                position=i;
                break;
            }
        }
        
        this.currentPlayerTwoPokemon.setHealth(this.currentPlayerTwoPokemon.getHealth()+((this.currentPlayerOnePokemon.getSpAttack()*-0.4)+this.currentPlayerTwoPokemon.getSpDefense()*0.1));
        this.listPlayerTwo.set(position, this.currentPlayerTwoPokemon);
        if(this.currentPlayerTwoPokemon.getHealth()<=0 && (this.listPlayerTwo.size()>0 && this.listPlayerOne.size()>0))
        {
            this.listPlayerTwo.remove(position);
            this.currentPlayerTwoPokemon=this.listPlayerTwo.get(this.listPlayerTwo.size()-1);
            this.jLabel2.setIcon(new ImageIcon(this.currentPlayerTwoPokemon.getPokeImage()));
        }
        this.jLabel2.setText(this.currentPlayerTwoPokemon.getName());
        this.jLabel5Player2Health.setText(currentPlayerTwoPokemon.getHealth()+"");
        this.repaint();
    }//GEN-LAST:event_jButton2SpAttackMouseClicked

    private void jButton4SpAttackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4SpAttackMouseClicked
        int position=0;
        for(int i =0;i<this.listPlayerOne.size();i++)
        {
            if(this.currentPlayerOnePokemon.equals(this.listPlayerOne.get(i)))
            {
                position=i;
                break;
            }
        }
        
        this.currentPlayerOnePokemon.setHealth(this.currentPlayerOnePokemon.getHealth()+((this.currentPlayerTwoPokemon.getSpAttack()*-0.4)+this.currentPlayerOnePokemon.getSpDefense()*0.1));
        this.listPlayerOne.set(position, this.currentPlayerOnePokemon);
        
        if(this.currentPlayerOnePokemon.getHealth()<=0 && (this.listPlayerTwo.size()>0 && this.listPlayerOne.size()>0))
        {
            this.listPlayerOne.remove(position);
            this.currentPlayerOnePokemon=this.listPlayerOne.get(this.listPlayerOne.size()-1);
            this.jLabel1.setIcon(new ImageIcon(this.currentPlayerOnePokemon.getPokeImage()));  
        }
        this.jLabel1.setText(this.currentPlayerOnePokemon.getName());
        this.jLabel4Player1Health.setText(this.currentPlayerOnePokemon.getHealth()+"");
        this.repaint();
    }//GEN-LAST:event_jButton4SpAttackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Attack;
    private javax.swing.JButton jButton2SpAttack;
    private javax.swing.JButton jButton3Attack;
    private javax.swing.JButton jButton4SpAttack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4Player1Health;
    private javax.swing.JLabel jLabel5Player2Health;
    private javax.swing.JList<Pokemon> jList1;
    private javax.swing.JList<Pokemon> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
