/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.iesjandula.pokemon_game;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import es.iesjandula.pokemon_game.models.Pokemon;
import es.iesjandula.pokemon_game.utils.PokemonException;
import lombok.Data;

/**
 *
 * @author David Martinez Flores
 */
@Data
public class PlayerTwoSelection extends javax.swing.JFrame implements Serializable
{
	/** Attribute logger */
	private static final Logger logger = LogManager.getLogger();

	/** Attribute mainTheme */
	private Clip mainTheme;

	/** Attribute playerTwoName */
	private String playerTwoName;

	/** Attribute temporalListModel */
	private DefaultListModel<Pokemon> temporalListModel = new DefaultListModel<>();

	/** Attribute playerOneSelection */
	private PlayerOneSelection playerOneSelection;

	/** Attribute listModel */
	private DefaultListModel<Pokemon> listModel = new DefaultListModel<>();

	/** Attribute listModel2 */
	private DefaultListModel<Pokemon> listModel2 = new DefaultListModel<>();

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel SpriteSelectedPlayerTwo;
	private javax.swing.ButtonGroup buttonGroupPlayerTwoSprites;
	private javax.swing.JButton jButtonRandom;
	private javax.swing.JButton jButtonRemove;
	private javax.swing.JButton jButtonRemoveAll;
	private javax.swing.JButton jButtonResetFilter;
	private javax.swing.JButton jButtonSelect;
	private javax.swing.JButton jButtonSelectionComplete;
	private javax.swing.JLabel jLabelAttack;
	private javax.swing.JLabel jLabelBackground;
	private javax.swing.JLabel jLabelChoseYourPokemon;
	private javax.swing.JLabel jLabelDefense;
	private javax.swing.JLabel jLabelFilter;
	private javax.swing.JLabel jLabelHealth;
	private javax.swing.JLabel jLabelPlayerName;
	private javax.swing.JLabel jLabelPlayerTwoName;
	private javax.swing.JLabel jLabelSpAttack;
	private javax.swing.JLabel jLabelSpDefense;
	private javax.swing.JLabel jLabelSpeed;
	private javax.swing.JList<Pokemon> jListAllPokemons;
	private javax.swing.JList<Pokemon> jListPlayerPokemons;
	private javax.swing.JMenu jMenu;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItemLoad;
	private javax.swing.JRadioButton jRadioButtonBlue;
	private javax.swing.JRadioButton jRadioButtonFemaleRanger;
	private javax.swing.JRadioButton jRadioButtonNormalFemale;
	private javax.swing.JRadioButton jRadioButtonRanger;
	private javax.swing.JRadioButton jRadioButtonRed;
	private javax.swing.JScrollPane jScrollPane;
	private javax.swing.JScrollPane jScrollPaneTwo;
	private javax.swing.JTextField jTextFieldFilter;
	private javax.swing.JTextField jTextFieldPlayerName;

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form PlayerTwoSelection
	 *
	 * @param playerOneSelection
	 */
	public PlayerTwoSelection(PlayerOneSelection playerOneSelection)
	{
		// --THE ORDER ITS IMPORTATNT-----
		this.initComponents();
		this.setTitle("Player Two Selection");
		this.setIconImage(Toolkit.getDefaultToolkit().getImage("./images/pokeball.png"));

		this.jLabelBackground.setIcon(new ImageIcon("./images/selectionBack2.jpg"));
		this.SpriteSelectedPlayerTwo.setIcon(new ImageIcon("./images/red.png"));
		this.playerTwoName = "Player Two";
		this.jLabelPlayerName.setText(this.playerTwoName);

		this.mainTheme = playerOneSelection.getMainTheme();
		this.playerOneSelection = playerOneSelection;

		this.setResizable(false);
		this.listModel.addAll(new Application().getPokemonList());
		this.jListAllPokemons.setModel(this.listModel);
		this.jListPlayerPokemons.setModel(this.listModel2);

		this.jumpPokemonAnimationThread();

		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		this.buttonGroupPlayerTwoSprites = new javax.swing.ButtonGroup();
		this.jLabelChoseYourPokemon = new javax.swing.JLabel();
		this.jButtonSelectionComplete = new javax.swing.JButton();
		this.jButtonRemove = new javax.swing.JButton();
		this.jButtonRemoveAll = new javax.swing.JButton();
		this.jLabelHealth = new javax.swing.JLabel();
		this.jLabelAttack = new javax.swing.JLabel();
		this.jLabelDefense = new javax.swing.JLabel();
		this.jScrollPane = new javax.swing.JScrollPane();
		this.jListAllPokemons = new javax.swing.JList<>();
		this.jLabelSpAttack = new javax.swing.JLabel();
		this.jLabelSpDefense = new javax.swing.JLabel();
		this.jButtonSelect = new javax.swing.JButton();
		this.jLabelSpeed = new javax.swing.JLabel();
		this.jScrollPaneTwo = new javax.swing.JScrollPane();
		this.jListPlayerPokemons = new javax.swing.JList<>();
		this.jTextFieldFilter = new javax.swing.JTextField();
		this.jLabelFilter = new javax.swing.JLabel();
		this.jButtonResetFilter = new javax.swing.JButton();
		this.jTextFieldPlayerName = new javax.swing.JTextField();
		this.jLabelPlayerTwoName = new javax.swing.JLabel();
		this.jLabelPlayerName = new javax.swing.JLabel();
		this.jRadioButtonRed = new javax.swing.JRadioButton();
		this.jRadioButtonBlue = new javax.swing.JRadioButton();
		this.SpriteSelectedPlayerTwo = new javax.swing.JLabel();
		this.jRadioButtonRanger = new javax.swing.JRadioButton();
		this.jRadioButtonFemaleRanger = new javax.swing.JRadioButton();
		this.jRadioButtonNormalFemale = new javax.swing.JRadioButton();
		this.jButtonRandom = new javax.swing.JButton();
		this.jLabelBackground = new javax.swing.JLabel();
		this.jMenuBar1 = new javax.swing.JMenuBar();
		this.jMenu = new javax.swing.JMenu();
		this.jMenuItemLoad = new javax.swing.JMenuItem();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		this.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		this.jLabelChoseYourPokemon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		this.jLabelChoseYourPokemon.setText("         CHOOSE YOUR POKEMON!");
		this.jLabelChoseYourPokemon
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		this.jLabelChoseYourPokemon.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
		this.getContentPane().add(this.jLabelChoseYourPokemon,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 355, 363, 165));

		this.jButtonSelectionComplete.setBackground(new java.awt.Color(51, 204, 0));
		this.jButtonSelectionComplete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jButtonSelectionComplete.setForeground(new java.awt.Color(255, 255, 255));
		this.jButtonSelectionComplete.setText("SELECTION COMPLETE");
		this.jButtonSelectionComplete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonSelectionComplete.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jButtonSelectionCompleteActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jButtonSelectionComplete,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 526, -1, 47));

		this.jButtonRemove.setBackground(new java.awt.Color(255, 153, 102));
		this.jButtonRemove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jButtonRemove.setForeground(new java.awt.Color(255, 255, 255));
		this.jButtonRemove.setText("REMOVE");
		this.jButtonRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonRemove.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerTwoSelection.this.jButtonRemoveMouseClicked(evt);
			}
		});
		this.getContentPane().add(this.jButtonRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 326, -1, -1));

		this.jButtonRemoveAll.setBackground(new java.awt.Color(255, 0, 51));
		this.jButtonRemoveAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jButtonRemoveAll.setForeground(new java.awt.Color(255, 255, 255));
		this.jButtonRemoveAll.setText("REMOVE ALL");
		this.jButtonRemoveAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonRemoveAll.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerTwoSelection.this.jButtonRemoveAllMouseClicked(evt);
			}
		});
		this.getContentPane().add(this.jButtonRemoveAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(799, 326, -1, -1));

		this.jLabelHealth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelHealth.setForeground(new java.awt.Color(0, 117, 0));
		this.jLabelHealth.setText("HEALTH");
		this.jLabelHealth.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelHealth.setOpaque(true);
		this.getContentPane().add(this.jLabelHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 355, 111, -1));

		this.jLabelAttack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelAttack.setForeground(new java.awt.Color(255, 0, 0));
		this.jLabelAttack.setText("ATTACK");
		this.jLabelAttack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelAttack.setOpaque(true);
		this.getContentPane().add(this.jLabelAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 381, 94, -1));

		this.jLabelDefense.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelDefense.setForeground(new java.awt.Color(51, 51, 255));
		this.jLabelDefense.setText("DEFENSE");
		this.jLabelDefense.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelDefense.setOpaque(true);
		this.getContentPane().add(this.jLabelDefense, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 433, 111, -1));

		this.jListAllPokemons.setBackground(new java.awt.Color(255, 200, 200));
		this.jListAllPokemons.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		this.jListAllPokemons.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jListAllPokemons.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerTwoSelection.this.jListAllPokemonsMouseClicked(evt);
			}
		});
		this.jScrollPane.setViewportView(this.jListAllPokemons);

		this.getContentPane().add(this.jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 421, 273));

		this.jLabelSpAttack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelSpAttack.setForeground(new java.awt.Color(255, 102, 0));
		this.jLabelSpAttack.setText("SP-ATTACK");
		this.jLabelSpAttack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelSpAttack.setOpaque(true);
		this.getContentPane().add(this.jLabelSpAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 407, 111, -1));

		this.jLabelSpDefense.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelSpDefense.setForeground(new java.awt.Color(0, 204, 204));
		this.jLabelSpDefense.setText("SP-DEFENSE");
		this.jLabelSpDefense.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelSpDefense.setOpaque(true);
		this.getContentPane().add(this.jLabelSpDefense, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 459, 130, -1));

		this.jButtonSelect.setBackground(new java.awt.Color(51, 153, 0));
		this.jButtonSelect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jButtonSelect.setForeground(new java.awt.Color(255, 255, 255));
		this.jButtonSelect.setText("SELECT");
		this.jButtonSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonSelect.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerTwoSelection.this.jButtonSelectMouseClicked(evt);
			}
		});
		this.getContentPane().add(this.jButtonSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 326, -1, -1));

		this.jLabelSpeed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		this.jLabelSpeed.setForeground(new java.awt.Color(248, 0, 243));
		this.jLabelSpeed.setText("SPEED");
		this.jLabelSpeed.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		this.jLabelSpeed.setOpaque(true);
		this.getContentPane().add(this.jLabelSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 485, 111, -1));

		this.jListPlayerPokemons.setBackground(new java.awt.Color(227, 227, 227));
		this.jListPlayerPokemons.setForeground(new java.awt.Color(0, 102, 0));
		this.jListPlayerPokemons.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jListPlayerPokemons.addMouseListener(new java.awt.event.MouseAdapter()
		{
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				PlayerTwoSelection.this.jListPlayerPokemonsMouseClicked(evt);
			}
		});
		this.jScrollPaneTwo.setViewportView(this.jListPlayerPokemons);

		this.getContentPane().add(this.jScrollPaneTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 41, 419, 273));

		this.jTextFieldFilter.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jTextFieldFilterActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jTextFieldFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 6, 136, -1));

		this.jLabelFilter.setBackground(new java.awt.Color(255, 204, 102));
		this.jLabelFilter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jLabelFilter.setText("FILTER:");
		this.jLabelFilter.setOpaque(true);
		this.getContentPane().add(this.jLabelFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 9, -1, -1));

		this.jButtonResetFilter.setText("RESET FILTER");
		this.jButtonResetFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonResetFilter.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jButtonResetFilterActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jButtonResetFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 6, -1, -1));

		this.jTextFieldPlayerName.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jTextFieldPlayerNameActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jTextFieldPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 6, 116, -1));

		this.jLabelPlayerTwoName.setBackground(new java.awt.Color(255, 204, 102));
		this.jLabelPlayerTwoName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jLabelPlayerTwoName.setText("Player Two Name:");
		this.jLabelPlayerTwoName.setOpaque(true);
		this.getContentPane().add(this.jLabelPlayerTwoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 9, -1, -1));

		this.jLabelPlayerName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		this.jLabelPlayerName.setText("       ");
		this.getContentPane().add(this.jLabelPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 9, 207, 20));

		this.buttonGroupPlayerTwoSprites.add(this.jRadioButtonRed);
		this.jRadioButtonRed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jRadioButtonRed.setSelected(true);
		this.jRadioButtonRed.setText("Red");
		this.jRadioButtonRed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jRadioButtonRed.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jRadioButtonRedActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jRadioButtonRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 381, -1, -1));

		this.buttonGroupPlayerTwoSprites.add(this.jRadioButtonBlue);
		this.jRadioButtonBlue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jRadioButtonBlue.setText("Blue");
		this.jRadioButtonBlue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jRadioButtonBlue.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jRadioButtonBlueActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jRadioButtonBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 414, -1, -1));

		this.SpriteSelectedPlayerTwo.setText(" ");
		this.getContentPane().add(this.SpriteSelectedPlayerTwo,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 355, 136, 196));

		this.buttonGroupPlayerTwoSprites.add(this.jRadioButtonRanger);
		this.jRadioButtonRanger.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jRadioButtonRanger.setText("Ranger");
		this.jRadioButtonRanger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jRadioButtonRanger.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jRadioButtonRangerActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jRadioButtonRanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 443, -1, -1));

		this.buttonGroupPlayerTwoSprites.add(this.jRadioButtonFemaleRanger);
		this.jRadioButtonFemaleRanger.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jRadioButtonFemaleRanger.setText("Female Ranger");
		this.jRadioButtonFemaleRanger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jRadioButtonFemaleRanger.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jRadioButtonFemaleRangerActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jRadioButtonFemaleRanger,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 472, -1, -1));

		this.buttonGroupPlayerTwoSprites.add(this.jRadioButtonNormalFemale);
		this.jRadioButtonNormalFemale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jRadioButtonNormalFemale.setText("Normal Female");
		this.jRadioButtonNormalFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jRadioButtonNormalFemale.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jRadioButtonNormalFemaleActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jRadioButtonNormalFemale,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 499, -1, -1));

		this.jButtonRandom.setBackground(new java.awt.Color(255, 0, 255));
		this.jButtonRandom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jButtonRandom.setForeground(new java.awt.Color(255, 255, 255));
		this.jButtonRandom.setText("RANDOM");
		this.jButtonRandom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		this.jButtonRandom.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jButtonRandomActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.jButtonRandom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 30));

		this.jLabelBackground.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		this.jLabelBackground.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
		this.getContentPane().add(this.jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -4, 920, 600));

		this.jMenu.setText("File");

		this.jMenuItemLoad.setText("Load State");
		this.jMenuItemLoad.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				PlayerTwoSelection.this.jMenuItemLoadActionPerformed(evt);
			}
		});
		this.jMenu.add(this.jMenuItemLoad);

		this.jMenuBar1.add(this.jMenu);

		this.setJMenuBar(this.jMenuBar1);

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Method jButtonRandomActionPerformed Used for get five random pokemons to
	 * selected pokemons
	 *
	 * @param evt
	 */
	private void jButtonRandomActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton6ActionPerformed
		int random = (int) ((Math.random() * 721) + 1);
		logger.info(random);
		List<Pokemon> randomList = new ArrayList<>();

		for (int i = 0; i < 5; i++)
		{
			random = (int) ((Math.random() * 721) + 1);
			randomList.add(this.listModel.get(random));
		}
		this.listModel2 = new DefaultListModel<>();
		this.listModel2.addAll(randomList);
		this.jListPlayerPokemons.setModel(this.listModel2);
	}// GEN-LAST:event_jButton6ActionPerformed

	/**
	 * Method jTextFieldFilterActionPerformed Used for filter the pokemon list
	 *
	 * @param evt
	 */
	private void jTextFieldFilterActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jTextField1ActionPerformed
		logger.info("Presiono Enter");
		this.temporalListModel = new DefaultListModel<>();

		for (int i = 0; i < this.listModel.size(); i++)
		{
			if (this.listModel.get(i).getName().toLowerCase().contains(this.jTextFieldFilter.getText().toLowerCase()))
			{
				this.temporalListModel.add(0, this.listModel.get(i));
			}
		}

		this.jListAllPokemons.setModel(this.temporalListModel);
	}// GEN-LAST:event_jTextField1ActionPerformed

	/**
	 * Method jButtonResetFilterActionPerformed Reset the filter
	 *
	 * @param evt
	 */
	private void jButtonResetFilterActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton5ActionPerformed
		this.jListAllPokemons.setModel(this.listModel);
		this.jTextFieldFilter.setText("");
	}// GEN-LAST:event_jButton5ActionPerformed

	/**
	 * Method jTextFieldPlayerNameActionPerformed Used for the player name with
	 * specific settings
	 *
	 * @param evt
	 */
	private void jTextFieldPlayerNameActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jTextField2ActionPerformed

		// --TRIM--FOR DELETE EMPTY NAMES AND SPACES---
		this.playerTwoName = this.jTextFieldPlayerName.getText().trim();

		// ---MAX 16 CHARS----
		if ((this.playerTwoName.length() <= 16) && !this.playerTwoName.isEmpty())
		{
			this.jLabelPlayerName.setText(this.playerTwoName);
		}
		else
		{
			// --SHOW POP UP WARNING----
			JOptionPane.showMessageDialog(null, "The selected name is too big or empty (16 chars max)");
		}

	}// GEN-LAST:event_jTextField2ActionPerformed

	/**
	 * Method jRadioButtonRedActionPerformed Change the sprite
	 *
	 * @param evt
	 */
	private void jRadioButtonRedActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jRadioButton1ActionPerformed
		this.SpriteSelectedPlayerTwo.setIcon(new ImageIcon("./images/red.png"));
	}// GEN-LAST:event_jRadioButton1ActionPerformed

	/**
	 * Method jRadioButtonBlueActionPerformed Change the sprite
	 *
	 * @param evt
	 */
	private void jRadioButtonBlueActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jRadioButton2ActionPerformed
		this.SpriteSelectedPlayerTwo.setIcon(new ImageIcon("./images/blue.png"));
	}// GEN-LAST:event_jRadioButton2ActionPerformed

	/**
	 * Method jRadioButtonRangerActionPerformed Change the sprite
	 *
	 * @param evt
	 */
	private void jRadioButtonRangerActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jRadioButton3ActionPerformed
		this.SpriteSelectedPlayerTwo.setIcon(new ImageIcon("./images/ranger.png"));
	}// GEN-LAST:event_jRadioButton3ActionPerformed

	/**
	 * Method jRadioButtonFemaleRangerActionPerformed Change the sprite
	 *
	 * @param evt
	 */
	private void jRadioButtonFemaleRangerActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jRadioButton4ActionPerformed
		this.SpriteSelectedPlayerTwo.setIcon(new ImageIcon("./images/femaleRanger.png"));
	}// GEN-LAST:event_jRadioButton4ActionPerformed

	/**
	 * Method jRadioButtonNormalFemaleActionPerformed Change the sprite
	 *
	 * @param evt
	 */
	private void jRadioButtonNormalFemaleActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jRadioButton5ActionPerformed
		this.SpriteSelectedPlayerTwo.setIcon(new ImageIcon("./images/normalFemale.png"));
	}// GEN-LAST:event_jRadioButton5ActionPerformed

	/**
	 * Method jMenuItemLoadActionPerformed Used for load the state
	 *
	 * @param evt
	 */
	private void jMenuItemLoadActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jMenuItem1ActionPerformed
		logger.info("CARGAR ESTADO");
		Application application = new Application();

		// --USE OBJECT LIST FOR STORE ALL THE OBJECTS---
		List<Object> partyList = null;
		try
		{
			partyList = application.loadState();
		}
		catch (PokemonException exception)
		{
			String error = "InterruptedException";
			PlayerTwoSelection.logger.error(error, exception);
		}

		if (partyList != null)
		{
			// --IF THE LOAD IS COMPLETED , LAUNCH THE PLAYER VERSUS PLAYER WITH THE PARTY
			// LIST---
			this.mainTheme.stop();
			PlayerVersusPlayer loadedPlayerVersusPlayer = new PlayerVersusPlayer(partyList);
			loadedPlayerVersusPlayer.setVisible(true);
			logger.info(partyList);
			this.dispose();
			JOptionPane.showMessageDialog(null, "STATE DATA LOADED!");

		}
		else
		{
			// --SHOW WARNING POP UP---
			JOptionPane.showMessageDialog(null, "THE STATE IS CORRUPTED OR DONT EXISTS ANY STATE!");
		}
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	/**
	 * Method jButtonSelectionCompleteActionPerformed Used for end the player
	 * selection
	 *
	 * @param evt
	 */
	private void jButtonSelectionCompleteActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton4ActionPerformed
		this.selectButtonSound();

		// --ONLY IF THE PLAYER SELECT MORE THAN 0 POKEMONS----
		if (this.listModel2.size() > 0)
		{
			this.mainTheme.stop();
			PlayerVersusPlayer playerVersusPlayer = new PlayerVersusPlayer(this);
			playerVersusPlayer.setVisible(true);
			this.dispose();
		}
		else
		{
			// ---SHOW POP UP WARNING---
			JOptionPane.showMessageDialog(this, "!OH , YOU NEED CHOOSE MINIMUM 1 POKEMON!");
		}
	}// GEN-LAST:event_jButton4ActionPerformed

	/**
	 * Method jButtonRemoveMouseClicked Used for remove the selected pokemon
	 *
	 * @param evt
	 */
	private void jButtonRemoveMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jButton2MouseClicked
		this.selectButtonSound();
		Pokemon selectedPokemon = this.jListPlayerPokemons.getSelectedValue();

		if (this.listModel2.contains(selectedPokemon))
		{
			for (int i = 0; i < this.listModel2.size(); i++)
			{
				Pokemon temporalPokemon = this.listModel2.get(i);
				if (temporalPokemon.equals(selectedPokemon))
				{
					this.listModel2.remove(i);
				}
			}
		}
	}// GEN-LAST:event_jButton2MouseClicked

	/**
	 * Method jButtonRemoveAllMouseClicked Used for remove all the pokemons seleted
	 *
	 * @param evt
	 */
	private void jButtonRemoveAllMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jButton3MouseClicked
		this.selectButtonSound();
		this.listModel2.removeAllElements();
	}// GEN-LAST:event_jButton3MouseClicked

	/**
	 * Method jListAllPokemonsMouseClicked Used for get the pokemon selected data
	 * from the all pokemon list to labels
	 *
	 * @param evt
	 */
	private void jListAllPokemonsMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jList1MouseClicked
		this.selectButtonSound();
		Pokemon selectedPokemon = this.jListAllPokemons.getSelectedValue();
		ImageIcon icon = new ImageIcon(selectedPokemon.getPokeImage());
		this.jLabelChoseYourPokemon.setIcon(icon);
		this.jLabelChoseYourPokemon.setText(selectedPokemon.getName());

		this.jLabelHealth.setText("Health: " + selectedPokemon.getHealth());
		this.jLabelAttack.setText("Attack: " + selectedPokemon.getAttack());
		this.jLabelDefense.setText("SP-Attack: " + selectedPokemon.getSpAttack());
		this.jLabelSpAttack.setText("Defense: " + selectedPokemon.getDefense());
		this.jLabelSpDefense.setText("SP-Defense: " + selectedPokemon.getSpDefense());
		this.jLabelSpeed.setText("Speed: " + selectedPokemon.getSpeed());
		this.repaint();

	}// GEN-LAST:event_jList1MouseClicked

	/**
	 * Method jButtonSelectMouseClicked Used for get the pokemon selected from the
	 * all pokemon list
	 *
	 * @param evt
	 */
	private void jButtonSelectMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jButton1MouseClicked
		this.selectButtonSound();
		Pokemon selectedPokemon = this.jListAllPokemons.getSelectedValue();

		// --IF THE POKEMON SELECTED ALRREADY EXIST ON THE SELECTED POKEMONS LAUNCH POP
		// UP WARNING---
		if (this.listModel2.contains(selectedPokemon))
		{
			JOptionPane.showMessageDialog(this, "You alrready select " + selectedPokemon.getName());
		}
		else if (this.listModel2.size() < 5)
		{
			this.listModel2.add(0, selectedPokemon);
			this.jListPlayerPokemons.setModel(this.listModel2);
			logger.info(this.listModel2);
		}
		else
		{
			JOptionPane.showMessageDialog(this, "You have 5 Pokemons selected!");
		}
	}// GEN-LAST:event_jButton1MouseClicked

	/**
	 * Method jListPlayerPokemonsMouseClicked Used for get the pokemon selected data
	 * from the selected pokemon list to labels
	 *
	 * @param evt
	 */
	private void jListPlayerPokemonsMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jList2MouseClicked
		this.selectButtonSound();
		Pokemon selectedPokemon = this.jListPlayerPokemons.getSelectedValue();
		if (selectedPokemon != null)
		{
			ImageIcon icon = new ImageIcon(selectedPokemon.getPokeImage());
			this.jLabelChoseYourPokemon.setIcon(icon);
			this.jLabelChoseYourPokemon.setText(selectedPokemon.getName());

			this.jLabelHealth.setText("Health: " + selectedPokemon.getHealth());
			this.jLabelAttack.setText("Attack: " + selectedPokemon.getAttack());
			this.jLabelDefense.setText("SP-Attack: " + selectedPokemon.getSpAttack());
			this.jLabelSpAttack.setText("Defense: " + selectedPokemon.getDefense());
			this.jLabelSpDefense.setText("SP-Defense: " + selectedPokemon.getSpDefense());
			this.jLabelSpeed.setText("Speed: " + selectedPokemon.getSpeed());
			this.repaint();
		}
	}// GEN-LAST:event_jList2MouseClicked

	/**
	 * Method selectButtonSound The buttons sound
	 */
	private void selectButtonSound()
	{

		AudioInputStream audioInputStream = null;
		try
		{
			audioInputStream = AudioSystem.getAudioInputStream(new File("./audio/butonSelect.wav"));
			Clip clip = AudioSystem.getClip();
			clip.open(audioInputStream);
			clip.start();
		}
		catch (UnsupportedAudioFileException exception)
		{
			String error = "UnsupportedAudioFileException";
			PlayerTwoSelection.logger.error(error, exception);
		}
		catch (IOException exception)
		{
			String error = "IOException";
			PlayerTwoSelection.logger.error(error, exception);
		}
		catch (LineUnavailableException exception)
		{
			String error = "LineUnavailableException";
			PlayerTwoSelection.logger.error(error, exception);
		}
		finally
		{
			try
			{
				audioInputStream.close();
			}
			catch (IOException exception)
			{
				String error = "IOException";
				PlayerTwoSelection.logger.error(error, exception);
			}
		}
	}

	/**
	 * Method jumpPokemonAnimationThread The jump pokemon animation
	 */
	private void jumpPokemonAnimationThread()
	{
		Thread jumpThread = new Thread(new Runnable()
		{
			@Override
			public void run()
			{
				int speed = 1;

				// --INFINITE LOOP , FOR INFINITE ANIMATION----
				while (true)
				{
					for (int i = 0; i < 10; i++)
					{

						PlayerTwoSelection.this.jLabelChoseYourPokemon.setLocation(
								PlayerTwoSelection.this.jLabelChoseYourPokemon.getX(),
								PlayerTwoSelection.this.jLabelChoseYourPokemon.getY() + speed);
						try
						{
							Thread.sleep(100);
						}
						catch (InterruptedException exception)
						{
							String error = "InterruptedException";
							PlayerTwoSelection.logger.error(error, exception);
						}
					}
					for (int i = 0; i < 10; i++)
					{

						PlayerTwoSelection.this.jLabelChoseYourPokemon.setLocation(
								PlayerTwoSelection.this.jLabelChoseYourPokemon.getX(),
								PlayerTwoSelection.this.jLabelChoseYourPokemon.getY() + (speed * -1));
						try
						{
							Thread.sleep(100);
						}
						catch (InterruptedException exception)
						{
							String error = "InterruptedException";
							PlayerTwoSelection.logger.error(error, exception);
						}
					}
				}
			}
		});
		jumpThread.start();
	}

}
