/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.iesjandula.pokemon_game;

import java.awt.Toolkit;
import java.util.List;

import javax.swing.ImageIcon;

import es.iesjandula.pokemon_game.models.Pokemon;

/**
 *
 * @author USUARIO
 */
public class PlayerOneKills extends javax.swing.JFrame
{
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPlayerOne;
    private javax.swing.JLabel jLabelPokemonFive;
    private javax.swing.JLabel jLabelPokemonFour;
    private javax.swing.JLabel jLabelPokemonOne;
    private javax.swing.JLabel jLabelPokemonThree;
    private javax.swing.JLabel jLabelPokemonTwo;
    // End of variables declaration//GEN-END:variables

	/**
	 * Creates new form PlayerOneKills
	 */
	public PlayerOneKills(List<Pokemon> listPlayer, int x, int y)
	{
		this.initComponents();
		this.setTitle("Player One Cards Defeated");
		this.setIconImage(Toolkit.getDefaultToolkit().getImage("./images/pokeball.png"));
		
		this.setResizable(false);
		this.setLocation(x, y);
		this.jLabelPokemonOne.setIcon(new ImageIcon("./images/0.png"));
		this.jLabelPokemonTwo.setIcon(new ImageIcon("./images/0.png"));
		this.jLabelPokemonThree.setIcon(new ImageIcon("./images/0.png"));
		this.jLabelPokemonFour.setIcon(new ImageIcon("./images/0.png"));
		this.jLabelPokemonFive.setIcon(new ImageIcon("./images/0.png"));
		if (listPlayer.size() > 0)
		{
			this.jLabelPokemonOne.setIcon(new ImageIcon(listPlayer.get(0).getPokeImage()));
                        this.jLabelPokemonOne.setToolTipText(listPlayer.get(0).getSpeed()+"");
		}
		if (listPlayer.size() > 1)
		{
			this.jLabelPokemonOne.setIcon(new ImageIcon(listPlayer.get(0).getPokeImage()));
			this.jLabelPokemonTwo.setIcon(new ImageIcon(listPlayer.get(1).getPokeImage()));
                        this.jLabelPokemonOne.setToolTipText(listPlayer.get(0).getSpeed()+"");
                        this.jLabelPokemonTwo.setToolTipText(listPlayer.get(1).getSpeed()+"");
		}
		if (listPlayer.size() > 2)
		{
			this.jLabelPokemonOne.setIcon(new ImageIcon(listPlayer.get(0).getPokeImage()));
			this.jLabelPokemonTwo.setIcon(new ImageIcon(listPlayer.get(1).getPokeImage()));
			this.jLabelPokemonThree.setIcon(new ImageIcon(listPlayer.get(2).getPokeImage()));
                        this.jLabelPokemonOne.setToolTipText(listPlayer.get(0).getSpeed()+"");
                        this.jLabelPokemonTwo.setToolTipText(listPlayer.get(1).getSpeed()+"");
                        this.jLabelPokemonThree.setToolTipText(listPlayer.get(2).getSpeed()+"");
                        
		}
		if (listPlayer.size() > 3)
		{
			this.jLabelPokemonOne.setIcon(new ImageIcon(listPlayer.get(0).getPokeImage()));
			this.jLabelPokemonTwo.setIcon(new ImageIcon(listPlayer.get(1).getPokeImage()));
			this.jLabelPokemonThree.setIcon(new ImageIcon(listPlayer.get(2).getPokeImage()));
			this.jLabelPokemonFour.setIcon(new ImageIcon(listPlayer.get(3).getPokeImage()));
                        this.jLabelPokemonOne.setToolTipText(listPlayer.get(0).getSpeed()+"");
                        this.jLabelPokemonTwo.setToolTipText(listPlayer.get(1).getSpeed()+"");
                        this.jLabelPokemonThree.setToolTipText(listPlayer.get(2).getSpeed()+"");
                        this.jLabelPokemonFour.setToolTipText(listPlayer.get(3).getSpeed()+"");

		}
		if (listPlayer.size() > 4)
		{
			this.jLabelPokemonOne.setIcon(new ImageIcon(listPlayer.get(0).getPokeImage()));
			this.jLabelPokemonTwo.setIcon(new ImageIcon(listPlayer.get(1).getPokeImage()));
			this.jLabelPokemonThree.setIcon(new ImageIcon(listPlayer.get(2).getPokeImage()));
			this.jLabelPokemonFour.setIcon(new ImageIcon(listPlayer.get(3).getPokeImage()));
			this.jLabelPokemonFive.setIcon(new ImageIcon(listPlayer.get(4).getPokeImage()));
                        this.jLabelPokemonOne.setToolTipText(listPlayer.get(0).getSpeed()+"");
                        this.jLabelPokemonTwo.setToolTipText(listPlayer.get(1).getSpeed()+"");
                        this.jLabelPokemonThree.setToolTipText(listPlayer.get(2).getSpeed()+"");
                        this.jLabelPokemonFour.setToolTipText(listPlayer.get(3).getSpeed()+"");
                        this.jLabelPokemonFive.setToolTipText(listPlayer.get(4).getSpeed()+"");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPokemonOne = new javax.swing.JLabel();
        jLabelPokemonThree = new javax.swing.JLabel();
        jLabelPokemonFour = new javax.swing.JLabel();
        jLabelPokemonFive = new javax.swing.JLabel();
        jLabelPokemonTwo = new javax.swing.JLabel();
        jLabelPlayerOne = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelPokemonOne.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelPokemonOne.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabelPokemonThree.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelPokemonThree.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabelPokemonFour.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelPokemonFour.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabelPokemonFive.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelPokemonFive.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabelPokemonTwo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelPokemonTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabelPlayerOne.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPlayerOne.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPlayerOne.setText("CARDS DEFEATED BY PLAYER ONE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPokemonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPokemonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPokemonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPokemonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPokemonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabelPlayerOne)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabelPlayerOne)
                .addGap(18, 18, 18)
                .addComponent(jLabelPokemonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPokemonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPokemonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelPokemonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPokemonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
}
